name: Softaculous aaPanel Plugin Development

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
  pull_request:
    branches:
      - main

env:
  PLUGIN_NAME: softaculous
  SOFTACULOUS_API: https://api.softaculous.com/v1
  PYTHON_VERSION: '3.11'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests PyYAML python-dotenv

    - name: Run Build Script
      run: python build_plugin.py

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Build and release version $(cat VERSION)"
        git push

    - name: Create Release
      run: |
        gh release create v$(cat VERSION) --title "Release v$(cat VERSION)" --notes "Release version $(cat VERSION)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
